#!/bin/bash

export CFLAGS=$1
export binaryName="ThrottleDemo"
rm -f *.o

for sourceObject in $(ls *.cpp)
do
	g++ -std=c++14 $CFLAGS -c $sourceObject
done

g++ -std=c++11 $CFLAGS *.o -o $binaryName -lpthread -L. -lCppConfigManager -lxerces-c -llog4cpp
strip $binaryName ; ./cleanupObjFiles
